## 00. PyTorch Fundamentals Exercise Solutions
### 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on torch.Tensor.
* The documentation on torch.cuda.

In [1]:
# read 


### 2. Create a random tensor with shape (7, 7).

In [4]:
# Import torch
import torch 

# Create a random tensor
X = torch.rand(size=(7, 7))
X, X.shape
     

(tensor([[0.8642, 0.7348, 0.5419, 0.7722, 0.7274, 0.0206, 0.0503],
         [0.6085, 0.9868, 0.7976, 0.5966, 0.4089, 0.3985, 0.9006],
         [0.6643, 0.3180, 0.9158, 0.7809, 0.3248, 0.6544, 0.1179],
         [0.4753, 0.5315, 0.9698, 0.1947, 0.7800, 0.9608, 0.4340],
         [0.0589, 0.0721, 0.0903, 0.4624, 0.1178, 0.1132, 0.9983],
         [0.1239, 0.0412, 0.3080, 0.9248, 0.8205, 0.6730, 0.2645],
         [0.4257, 0.3646, 0.4716, 0.1185, 0.5514, 0.8574, 0.5002]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
y = torch.rand(size=(1,7))
y, y.shape

(tensor([[0.5863, 0.3616, 0.4342, 0.6858, 0.7355, 0.3910, 0.3133]]),
 torch.Size([1, 7]))

In [9]:
mul = torch.matmul(X,y.T)
mul , mul.shape

(tensor([[2.0961],
         [2.2078],
         [1.9693],
         [2.1108],
         [0.8605],
         [1.8050],
         [1.5651]]),
 torch.Size([7, 1]))

### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [10]:

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape
     

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [12]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [13]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min
     

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min
     

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
